In [1]:
import pandas as pd

In [66]:
df = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv")

In [58]:
df

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [30]:
df["Element Code"].corr(df["Y2016"])

0.02344399758496138

In [31]:
df["Element Code"].corr(df["Y2015"])

0.02388919930163995

In [32]:
df["Element Code"].corr(df["Y2017"])

0.024254007760045757

In [33]:
df["Element Code"].corr(df["Y2014"])

0.024456819495221736

In [51]:
df2 = df[["Area","Y2017"]]
df2.groupby("Area").sum()

                                  Y2017
Area
Algeria                       325644.27
Angola                        229159.57
Benin                         124771.22
Botswana                       22101.30
Burkina Faso                  101855.07
Cabo Verde                     14650.74
Cameroon                      232030.43
Central African Republic       29937.00
Chad                           71594.68
Comoros                           59.84
Congo                          41181.68
Cï¿½te d'Ivoire                 224599.01
Djibouti                       22729.91
Egypt                         866379.92
Eswatini                       54343.33
Ethiopia                      448683.76
Ethiopia PDR                       0.00
Gabon                          27979.64
Gambia                         23154.18
Ghana                         337599.06
Guinea                         98138.87
Guinea-Bissau                  19102.77
Kenya                         264660.66
Lesotho                        21267.96
Liberia                        29342.20
Madagascar                    131197.73
Malawi                        181098.71
Mali                          149928.33
Mauritania                    156665.46
Mauritius                      51114.83
Morocco                       388495.36
Mozambique                    161407.98
Namibia                        29874.89
Niger                         126707.58
Nigeria                      1483268.23
Rwanda                         73663.69
Sao Tome and Principe          12662.63
Senegal                        95681.15
Seychelles                       442.34
Sierra Leone                   55311.33
South Africa                  517590.54
Sudan                         239931.92
Sudan (former)                     0.00
Togo                           49841.88
Tunisia                       124167.20
Uganda                        213950.38
United Republic of Tanzania   322616.85
Zambia                        103223.77
Zimbabwe                       75919.34

In [59]:
df.groupby("Element").sum()

,Area Code,Area,Item Code,Item,Element Code,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,,,,
Domestic supply quantity,708993,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,14197445,PopulationCereals - Excluding BeerWheat and pr...,28068795,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,11840553,Cereals - Excluding BeerWheat and productsRice...,26026133,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13535000,Grand TotalVegetal ProductsAnimal ProductsCere...,3435732,g/capita/dayg/capita/dayg/capita/dayg/capita/d...,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,3538507,Cereals - Excluding BeerWheat and productsRice...,7282199,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13285035,Cereals - Excluding BeerWheat and productsRice...,25406622,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13511060,Grand TotalVegetal ProductsAnimal ProductsCere...,3329296,kcal/capita/daykcal/capita/daykcal/capita/dayk...,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13185401,Cereals - Excluding BeerWheat and productsRice...,3163725,kgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkg...,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13795966,Cereals - Excluding BeerWheat and productsRice...,28834929,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,5424803,Cereals - Excluding BeerWheat and productsRice...,10292107,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,4729749,Cereals - Excluding BeerWheat and productsStar...,8926728,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,5350416,Cereals - Excluding BeerWheat and productsRice...,10313310,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,10450053,Cereals - Excluding BeerWheat and productsRice...,21388191,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13535000,Grand TotalVegetal ProductsAnimal ProductsCere...,3385502,g/capita/dayg/capita/dayg/capita/dayg/capita/d...,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,12421089,Cereals - Excluding BeerWheat and productsRice...,24066350,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,2035933,Cereals - Excluding BeerWheat and productsRice...,4211574,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,11329527,Cereals - Excluding BeerWheat and productsRice...,21464704,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,AlgeriaAngolaBeninBotswanaBurkina FasoCabo Ver...,112545,PopulationPopulationPopulationPopulationPopula...,22995,1000 persons1000 persons1000 persons1000 perso...,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,AngolaAngolaBotswanaBotswanaBotswanaBotswanaBo...,1486528,OilcropsGroundnuts (Shelled Eq)Cereals - Exclu...,2869905,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,416.00,349.00,89.00,91.00,90.00

In [71]:
len(df["Area"].unique())

49

In [86]:
x = df.groupby("Element").first()
x

,Area Code,Area,Item Code,Item,Element Code,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,,,,
Domestic supply quantity,4,Algeria,2501,Population,5301,1000 tonnes,0.00,0.00,0.00,0.00,0.00
Export Quantity,4,Algeria,2905,Cereals - Excluding Beer,5911,1000 tonnes,3.00,7.00,7.00,10.00,17.00
Fat supply quantity (g/capita/day),4,Algeria,2901,Grand Total,684,g/capita/day,80.06,79.36,77.40,80.19,77.28
Feed,4,Algeria,2905,Cereals - Excluding Beer,5521,1000 tonnes,4725.00,5070.00,4838.00,4667.00,5266.00
Food,4,Algeria,2905,Cereals - Excluding Beer,5142,1000 tonnes,8546.00,8729.00,9001.00,8941.00,9219.00
Food supply (kcal/capita/day),4,Algeria,2901,Grand Total,664,kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
Food supply quantity (kg/capita/yr),4,Algeria,2905,Cereals - Excluding Beer,645,kg,219.56,219.72,221.98,216.02,218.31
Import Quantity,4,Algeria,2905,Cereals - Excluding Beer,5611,1000 tonnes,12604.00,13983.00,13523.00,13039.00,13182.00
Losses,4,Algeria,2905,Cereals - Excluding Beer,5123,1000 tonnes,1084.00,1203.00,1148.00,1121.00,1253.00
Other uses (non-food),4,Algeria,2905,Cereals - Excluding Beer,5154,1000 tonnes,787.00,847.00,835.00,840.00,951.00
Processing,4,Algeria,2905,Cereals - Excluding Beer,5131,1000 tonnes,35.00,38.00,37.00,33.00,44.00
Production,4,Algeria,2905,Cereals - Excluding Beer,5511,1000 tonnes,3436.00,3761.00,3445.00,3478.00,6065.00
Protein supply quantity (g/capita/day),4,Algeria,2901,Grand Total,674,g/capita/day,94.90,94.35,94.72,92.82,91.83
Residuals,4,Algeria,2905,Cereals - Excluding Beer,5170,1000 tonnes,0.00,0.00,0.00,0.00,-8.00
Seed,4,Algeria,2905,Cereals - Excluding Beer,5527,1000 tonnes,177.00,189.00,197.00,202.00,278.00
Stock Variation,4,Algeria,2905,Cereals - Excluding Beer,5072,1000 tonnes,684.00,1663.00,905.00,705.00,2226.00
Total Population - Both sexes,4,Algeria,2501,Population,511,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
Tourist consumption,7,Angola,2913,Oilcrops,5171,1000 tonnes,0.00,0.00,0.00,0.00,0.00

In [87]:
array  = ([[94, 89, 63],

             [93, 92, 48],

             [92, 94, 56]])

In [122]:
array[:1][1:]

[]

In [123]:
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [124]:
df = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv")

In [134]:
df2 = df[["Y2017", "Area"]]

In [154]:
df.groupby("Item").first().sum()

KeyError: 'Item == Wine'

In [131]:
grouped_data

Empty DataFrame
Columns: [Area Code, Area, Item Code, Item, Element Code, Unit, Y2014, Y2015, Y2016, Y2017, Y2018]
Index: []